program eXactWMS;

uses
  MidasLib,
  Vcl.Forms,
  Windows,
  Dialogs,
  WinApi.Activex,
  uFrmSobre in 'View\uFrmSobre.pas' {frmSobre},
  Vcl.Themes,
  Vcl.Styles,
  uLoggerSingleton in 'Controller\uLoggerSingleton.pas',
  uFuncoes in 'Controller\uFuncoes.pas',
  UFrmConfirmacao in 'View\UFrmConfirmacao.pas' {FrmConfirmacao},
  LaboratorioCtrl in 'Controller\LaboratorioCtrl.Pas',
  LaboratoriosClass in 'Model\LaboratoriosClass.Pas',
  UFrmBase in 'View\UFrmBase.pas' {FrmBase},
  uDmBase in 'DAO\uDmBase.pas' {DmBase: TDataModule},
  uDmeXactWMS in 'DAO\uDmeXactWMS.pas' {DmeXactWMS: TDataModule},
  uFrmLaboratorio in 'View\uFrmLaboratorio.pas' {FrmLaboratorio},
  PessoaTipoClass in 'Model\PessoaTipoClass.pas',
  PessoaTipoCtrl in 'Controller\PessoaTipoCtrl.pas',
  uFrmPessoaTipo in 'View\uFrmPessoaTipo.pas' {FrmPessoaTipo},
  PessoaCtrl in 'Controller\PessoaCtrl.Pas',
  PessoaClass in 'Model\PessoaClass.Pas',
  uFrmPessoa in 'View\uFrmPessoa.pas' {FrmPessoa},
  uFrmOperacaoNatureza in 'View\uFrmOperacaoNatureza.pas' {FrmOperacaoNatureza},
  uFrmOperacaoTipo in 'View\uFrmOperacaoTipo.pas' {FrmOperacaoTipo},
  uDistanceMatrixGoogle in 'Model\uDistanceMatrixGoogle.pas',
  ConfiguracaoClass in 'Model\ConfiguracaoClass.pas',
  uFrmSair in 'View\uFrmSair.pas' {FrmSair},
  uFrmProduto in 'View\uFrmProduto.pas' {FrmProduto},
  ProdutoCtrl in 'Controller\ProdutoCtrl.pas',
  ProdutoClass in 'Model\ProdutoClass.pas',
  ProdutoTipoClass in 'Model\ProdutoTipoClass.pas',
  MedicamentoTipoClass in 'Model\MedicamentoTipoClass.pas',
  UnidadeClass in 'Model\UnidadeClass.pas',
  EnderecamentoZonaClass in 'Model\EnderecamentoZonaClass.pas',
  EnderecoClass in 'Model\EnderecoClass.pas',
  EnderecoEstruturaClass in 'Model\EnderecoEstruturaClass.pas',
  DesenhoArmazemClass in 'Model\DesenhoArmazemClass.pas',
  uFrmProcesso in 'View\uFrmProcesso.pas' {FrmProcesso},
  uFrmControleArmazenagem in 'View\uFrmControleArmazenagem.pas' {FrmControleArmazenagem},
  LotesClass in 'Model\LotesClass.pas',
  LoteCtrl in 'Controller\LoteCtrl.pas',
  ProdutoTipoCtrl in 'Controller\ProdutoTipoCtrl.pas',
  uFrmEntrada in 'View\uFrmEntrada.pas' {FrmEntrada},
  EntradaCtrl in 'Controller\EntradaCtrl.pas',
  EntradaClass in 'Model\EntradaClass.pas',
  OperacaoTipoCtrl in 'Controller\OperacaoTipoCtrl.Pas',
  OperacaoNaturezaCtrl in 'Controller\OperacaoNaturezaCtrl.Pas',
  OperacaoNaturezaClass in 'Model\OperacaoNaturezaClass.Pas',
  OperacaoTipoClass in 'Model\OperacaoTipoClass.Pas',
  EntradaItensCtrl in 'Controller\EntradaItensCtrl.pas',
  EntradaItensClass in 'Model\EntradaItensClass.pas',
  uLaboratorioDAO in 'DAORESTFULL\uLaboratorioDAO.pas',
  uEntradaDAO in 'DAORESTFULL\uEntradaDAO.pas',
  uEntradaItensDAO in 'DAORESTFULL\uEntradaItensDAO.pas',
  ProdutoCodBarrasClass in 'Model\ProdutoCodBarrasClass.pas',
  ProdutoCodBarrasDAO in 'DAORESTFULL\ProdutoCodBarrasDAO.pas',
  ProdutoCodBarrasCtrl in 'Controller\ProdutoCodBarrasCtrl.pas',
  RastroCtrl in 'Controller\RastroCtrl.pas',
  MedicamentoTipoCtrl in 'Controller\MedicamentoTipoCtrl.pas',
  uFrmConfiguracao in 'View\uFrmConfiguracao.pas' {FrmConfiguracao},
  ConfiguracaoCtrl in 'Controller\ConfiguracaoCtrl.pas',
  uFrmeXactWMS in 'uFrmeXactWMS.pas' {FrmeXactWMS},
  uFrmLogin in 'View\uFrmLogin.pas' {FrmLogin},
  UsuarioCtrl in 'Controller\UsuarioCtrl.pas',
  UsuarioClass in 'Model\UsuarioClass.pas',
  uFrmUsuario in 'View\uFrmUsuario.pas' {FrmUsuario},
  EnderecoCtrl in 'Controller\EnderecoCtrl.pas',
  uEnderecoDAO in 'DAORESTFULL\uEnderecoDAO.pas',
  uFrmRelBase in 'Report\uFrmRelBase.pas' {FrmRelBase},
  EnderecamentoRuaClass in 'Model\EnderecamentoRuaClass.pas',
  EnderecamentoRuaCtrl in 'Controller\EnderecamentoRuaCtrl.pas',
  EnderecoRuaDAO in 'DAORESTFULL\EnderecoRuaDAO.pas',
  uFrmPedidoCubagem in 'View\uFrmPedidoCubagem.pas' {FrmPedidoCubagem},
  PedidoSaidaCtrl in 'Controller\PedidoSaidaCtrl.pas',
  PedidoSaidaClass in 'Model\PedidoSaidaClass.pas',
  PedidoProdutoCtrl in 'Controller\PedidoProdutoCtrl.pas',
  uPedidoProdutoDAO in 'DAORESTFULL\uPedidoProdutoDAO.pas',
  uPedidoSaidaDAO in 'DAORESTFULL\uPedidoSaidaDAO.pas',
  PedidoClass in 'Model\PedidoClass.pas',
  PedidoProdutoClass in 'Model\PedidoProdutoClass.pas',
  uFrmRotas in 'View\uFrmRotas.pas' {FrmRotas},
  RotaCtrl in 'Controller\RotaCtrl.pas',
  RotaClass in 'Model\RotaClass.pas',
  uRotaDAO in 'DAORESTFULL\uRotaDAO.pas',
  VolumeEmbalagemClass in 'Model\VolumeEmbalagemClass.pas',
  VolumeEmbalagemCtrl in 'Controller\VolumeEmbalagemCtrl.pas',
  uVolumeEmbalagemDAO in 'DAORESTFULL\uVolumeEmbalagemDAO.pas',
  uFrmVolumeEmbalagem in 'View\uFrmVolumeEmbalagem.pas' {FrmVolumeEmbalagem},
  RastroClass in 'Model\RastroClass.pas',
  UnidadeCtrl in 'Controller\UnidadeCtrl.pas',
  EnderecamentoZonaCtrl in 'Controller\EnderecamentoZonaCtrl.pas',
  EnderecamentoEstruturaCtrl in 'Controller\EnderecamentoEstruturaCtrl.pas',
  EnderecoEstruturaDAO in 'DAORESTFULL\EnderecoEstruturaDAO.pas',
  uFrmSeparacaoDesktop in 'View\uFrmSeparacaoDesktop.pas' {FrmSeparacaoDesktop},
  EmbalagemCaixaClass in 'Model\EmbalagemCaixaClass.pas',
  PedidoVolumeClass in 'Model\PedidoVolumeClass.pas',
  uFrmReportBase in 'Report\uFrmReportBase.pas' {FrmReportBase},
  uFrmFREnderecamentos in 'Report\uFrmFREnderecamentos.pas' {FrmFREnderecamentos},
  EmbalagemCaixaCtrl in 'Controller\EmbalagemCaixaCtrl.pas',
  CaixaEmbalagemDAO in 'DAORESTFULL\CaixaEmbalagemDAO.pas',
  PedidoVolumeCtrl in 'Controller\PedidoVolumeCtrl.pas',
  PedidoVolumeDAO in 'DAORESTFULL\PedidoVolumeDAO.pas',
  PedidoVolumeSeparacaoClass in 'Model\PedidoVolumeSeparacaoClass.pas',
  PedidoVolumeSeparacaoCtrl in 'Controller\PedidoVolumeSeparacaoCtrl.pas',
  PedidoVolumeSeparacaoDAO in 'DAORESTFULL\PedidoVolumeSeparacaoDAO.pas',
  uFrmRelPedidos in 'Report\uFrmRelPedidos.pas' {FrmRelPedidos},
  EstoqueClass in 'Model\EstoqueClass.pas',
  EstoqueCtrl in 'Controller\EstoqueCtrl.pas',
  EstoqueDAO in 'DAORESTFULL\EstoqueDAO.pas',
  TopicosCtrl in 'Controller\TopicosCtrl.pas',
  PerfilClass in 'Model\PerfilClass.pas',
  FuncionalidadeClass in 'Model\FuncionalidadeClass.pas',
  TopicosClass in 'Model\TopicosClass.pas',
  PerfilCtrl in 'Controller\PerfilCtrl.pas',
  FuncionalidadeCtrl in 'Controller\FuncionalidadeCtrl.pas',
  TopicosDAO in 'DAORESTFULL\TopicosDAO.pas',
  PerfilDAO in 'DAORESTFULL\PerfilDAO.pas',
  FuncionalidadeDAO in 'DAORESTFULL\FuncionalidadeDAO.pas',
  uFrmTopicos in 'View\uFrmTopicos.pas' {FrmTopicos},
  uFrmFuncionalidades in 'View\uFrmFuncionalidades.pas' {FrmFuncionalidades},
  uFrmPerfil in 'View\uFrmPerfil.pas' {FrmPerfil},
  uFrmFornecedor in 'View\uFrmFornecedor.pas' {FrmFornecedor},
  uCepAbertoClass in 'Model\uCepAbertoClass.pas',
  EnderecoTipoCtrl in 'Controller\EnderecoTipoCtrl.pas',
  PessoaEnderecoCtrl in 'Controller\PessoaEnderecoCtrl.pas',
  PessoaEnderecoDAO in 'DAORESTFULL\PessoaEnderecoDAO.pas',
  PessoaTelefoneCtrl in 'Controller\PessoaTelefoneCtrl.pas',
  PessoaTelefoneDAO in 'DAORESTFULL\PessoaTelefoneDAO.pas',
  uFrmTransportadora in 'View\uFrmTransportadora.pas' {FrmTransportadora},
  VeiculoClass in 'Model\VeiculoClass.pas',
  VeiculoCtrl in 'Controller\VeiculoCtrl.pas',
  VeiculoDAO in 'DAORESTFULL\VeiculoDAO.pas',
  uFrmVeiculo in 'View\uFrmVeiculo.pas' {FrmVeiculo},
  uFrmMotorista in 'View\uFrmMotorista.pas' {FrmMotorista},
  uFrmCheckOut in 'View\uFrmCheckOut.pas' {FrmCheckOut},
  uFrmExpedicao in 'View\uFrmExpedicao.pas' {FrmExpedicao},
  uFrmRelPlanilhaCega in 'Report\uFrmRelPlanilhaCega.pas' {FrmRelPlanilhaCega},
  uFrmCargaMontar in 'View\uFrmCargaMontar.pas' {FrmCargaMontar},
  Providers.Models.Token in 'src\providers\models\Providers.Models.Token.pas',
  Providers.Request.Intf in 'src\providers\request\Providers.Request.Intf.pas',
  Providers.Request in 'src\providers\request\Providers.Request.pas',
  Providers.Session in 'src\providers\Providers.Session.pas',
  Services.Base in 'src\Services\Services.Base.pas' {ServiceBase: TDataModule},
  Services.Base.Cadastro in 'src\Services\Services.Base.Cadastro.pas' {ServiceBaseCadastro: TDataModule},
  Views.Base in 'src\Views\Views.Base.pas' {FrmBase4D},
  Views.Base.Cadastro in 'src\Views\Views.Base.Cadastro.pas' {FrmBaseCadastro},
  Views.Pequisa.Laboratorio in 'src\Views\Views.Pequisa.Laboratorio.pas' {FrmPesquisaLaboratorio},
  Services.Laboratorios in 'src\Services\Services.Laboratorios.pas' {ServiceLaboratorios: TDataModule},
  Services.Rotas in 'src\Services\Services.Rotas.pas' {ServiceRotas: TDataModule},
  Views.Pequisa.Rotas in 'src\Views\Views.Pequisa.Rotas.pas' {FrmPesquisaRotas},
  Services.Pessoas in 'src\Services\Services.Pessoas.pas' {ServicePessoas: TDataModule},
  Views.Pequisa.Pessoas in 'src\Views\Views.Pequisa.Pessoas.pas' {FrmPesquisaPessoas},
  Services.Veiculos in 'src\Services\Services.Veiculos.pas' {ServicesVeiculos: TDataModule},
  Views.Pequisa.Veiculos in 'src\Views\Views.Pequisa.Veiculos.pas' {FrmPesquisaVeiculos},
  UFrmBase4D in 'View\UFrmBase4D.pas' {FrmBasePSV},
  CargasClass in 'Model\CargasClass.pas',
  CargasCtrl in 'Controller\CargasCtrl.pas',
  CargasDAO in 'DAORESTFULL\CargasDAO.pas',
  uFrmCargaCarregar in 'View\uFrmCargaCarregar.pas' {FrmCargaCarregar},
  uFrmRelReposicaoDemanda in 'Report\uFrmRelReposicaoDemanda.pas' {FrmRelReposicaoDemanda},
  uFrmRelProdutoSemPicking in 'Report\uFrmRelProdutoSemPicking.pas' {FrmRelProdutoSemPicking},
  uFrmRelRupturaAbastecimento in 'Report\uFrmRelRupturaAbastecimento.pas' {FrmRelRupturaAbastecimento},
  uFrmRelColetaPulmao in 'Report\uFrmRelColetaPulmao.pas' {FrmRelColetaPulmao},
  uFrmRelApanhePicking in 'Report\uFrmRelApanhePicking.pas' {FrmRelApanhePicking},
  Services.Processos in 'src\Services\Services.Processos.pas' {ServiceProcessos: TDataModule},
  Views.Pequisa.Processos in 'src\Views\Views.Pequisa.Processos.pas' {FrmPesquisaProcessos},
  ProcessoCtrl in 'Controller\ProcessoCtrl.pas',
  ProcessoClass in 'Model\ProcessoClass.pas',
  ProcessoDAO in 'DAORESTFULL\ProcessoDAO.pas',
  uFrmRelResumoPedidos in 'Report\uFrmRelResumoPedidos.pas' {FrmRelResumoPedidos},
  uFrmRelAnaliseRessuprimento in 'Report\uFrmRelAnaliseRessuprimento.pas' {FrmRelAnaliseRessuprimento},
  uFrmRelestoque in 'Report\uFrmRelestoque.pas' {FrmRelEstoque},
  Services.Produtos in 'src\Services\Services.Produtos.pas' {ServiceProdutos: TDataModule},
  Views.Pequisa.Produtos in 'src\Views\Views.Pequisa.Produtos.pas' {FrmPesquisaProduto},
  Services.Enderecos in 'src\Services\Services.Enderecos.pas' {ServiceEnderecos: TDataModule},
  Views.Pequisa.Endereco in 'src\Views\Views.Pequisa.Endereco.pas' {FrmPesquisaEndereco},
  Services.EnderecamentoEstruturas in 'src\Services\Services.EnderecamentoEstruturas.pas' {ServiceEnderecamentoEstruturas: TDataModule},
  Views.Pequisa.EnderecamentoEstruturas in 'src\Views\Views.Pequisa.EnderecamentoEstruturas.pas' {FrmPesquisaEnderecamentoEstruturas},
  Services.EnderecamentoZonas in 'src\Services\Services.EnderecamentoZonas.pas' {ServiceEnderecamentoZonas: TDataModule},
  Views.Pequisa.EnderecamentoZonas in 'src\Views\Views.Pequisa.EnderecamentoZonas.pas' {FrmPesquisaEnderecamentoZonas},
  uLibThreadCustom in 'Model\uLibThreadCustom.pas',
  uFrmRelEspelhoEntrada in 'Report\uFrmRelEspelhoEntrada.pas' {FrmRelEspelhoEntrada},
  uFrmReposicao in 'View\uFrmReposicao.pas' {FrmReposicao},
  uFrmEnderecamento in 'View\uFrmEnderecamento.pas' {FrmEnderecamento},
  Services.EnderecamentoRuas in 'src\Services\Services.EnderecamentoRuas.pas' {ServiceEnderecamentoRuas: TDataModule},
  Views.Pequisa.EnderecamentoRuas in 'src\Views\Views.Pequisa.EnderecamentoRuas.pas' {FrmPesquisaEnderecamentoRuas},
  uFrmRelTagProduto in 'Report\uFrmRelTagProduto.pas' {FrmRelTagProduto},
  DesenhoArmazemCtrl in 'Controller\DesenhoArmazemCtrl.pas',
  DesenhoArmazemDAO in 'DAORESTFULL\DesenhoArmazemDAO.pas',
  Services.DesenhoArmazem in 'src\Services\Services.DesenhoArmazem.pas' {ServiceDesenhoArmazem: TDataModule},
  Views.Pequisa.DesenhoArmazem in 'src\Views\Views.Pequisa.DesenhoArmazem.pas' {FrmPesquisaDesenhoArmazem},
  Vcl.DialogMessage in 'Model\Vcl.DialogMessage.pas',
  uFrmInventario in 'View\uFrmInventario.pas' {FrmInventario},
  InventarioCtrl in 'Controller\InventarioCtrl.pas',
  InventarioClass in 'Model\InventarioClass.pas',
  InventarioDAO in 'DAORESTFULL\InventarioDAO.pas',
  uFrmEnderecamentoMenu in 'View\uFrmEnderecamentoMenu.pas' {FrmEnderecamentoMenu},
  uFrmDesenhoArmazem in 'View\uFrmDesenhoArmazem.pas' {FrmDesenhoArmazem},
  uFrmEnderecamentoRuas in 'View\uFrmEnderecamentoRuas.pas' {FrmEnderecamentoRuas},
  uFrmEnderecamentoZonas in 'View\uFrmEnderecamentoZonas.pas' {FrmEnderecamentoZonas},
  uFrmDevolucao in 'View\uFrmDevolucao.pas' {FrmDevolucao},
  DevolucaoCtrl in 'Controller\DevolucaoCtrl.pas',
  DevolucaoDAO in 'DAORESTFULL\DevolucaoDAO.pas',
  operacaonaturezamotivoClass in 'Model\operacaonaturezamotivoClass.Pas',
  operacaonaturezamotivoCtrl in 'Controller\operacaonaturezamotivoCtrl.Pas',
  operacaonaturezamotivoDAO in 'DAORESTFULL\operacaonaturezamotivoDAO.Pas',
  eXactWMSDAO in 'DAORESTFULL\eXactWMSDAO.pas',
  uFrmRelMapaCarga in 'Report\uFrmRelMapaCarga.pas' {FrmRelMapaCarga},
  uFrmRelCortes in 'Report\uFrmRelCortes.pas' {FrmRelCortes},
  uFrmChekOut_Sobra in 'Report\uFrmChekOut_Sobra.pas' {FrmCheckOut_Sobras},
  uFrmRelMapaSeparacao in 'Report\uFrmRelMapaSeparacao.pas' {FrmRelMapaSeparacao},
  Services.Pedido in 'src\Services\Services.Pedido.pas' {ServicePedidos: TDataModule},
  Service.Cargas in 'src\Services\Service.Cargas.pas' {ServiceCargas: TDataModule},
  Views.Pequisa.Cargas in 'src\Views\Views.Pequisa.Cargas.pas' {FrmPesquisaCargas},
  uFrmRelResumoProducao in 'Report\uFrmRelResumoProducao.pas' {FrmRelResumoProducao},
  uFrmRelEvolucaoRessuprimentos in 'Report\uFrmRelEvolucaoRessuprimentos.pas' {FrmRelEvolucaoRessuprimentos},
  UFrmMensagemSis in 'View\UFrmMensagemSis.pas' {FrmMensagemSis},
  uFrmCorrecaoLotes in 'View\uFrmCorrecaoLotes.pas' {FrmCorrecaoLotes},
  uFrmRelRecebimentos in 'Report\uFrmRelRecebimentos.pas' {FrmRelRecebimentos},
  uFrmRelProdutos in 'Report\uFrmRelProdutos.pas' {FrmRelProdutos},
  uFrmRelReposicaoColeta in 'Report\uFrmRelReposicaoColeta.pas' {FrmRelReposicaoColeta},
  uFrmRelResumoSeparacao in 'Report\uFrmRelResumoSeparacao.pas' {FrmRelResumoSeparacao},
  uFrmRelDesempenhoExpedicao in 'Report\uFrmRelDesempenhoExpedicao.pas' {FrmRelDesempenhoExpedicao},
  uFrmAuditoriaSaidaPorProduto in 'Report\uFrmAuditoriaSaidaPorProduto.pas' {FrmAuditoriaSaidaPorProduto},
  uFrmPrintTAG in 'Report\uFrmPrintTAG.pas' {FrmPrintTag},
  uFrmRelDshCheckOut in 'Report\uFrmRelDshCheckOut.pas' {FrmRelDshCheckOut},
  uFrmNovidades in 'View\uFrmNovidades.pas' {FrmNovidades},
  NovidadesCtrl in 'Controller\NovidadesCtrl.pas',
  Service.Novidades in 'src\Services\Service.Novidades.pas' {ServiceNovidades: TDataModule},
  uFrmRelEtiquetaArmazenagem in 'Report\uFrmRelEtiquetaArmazenagem.pas' {FrmRelEtiquetaArmazenagem},
  uFrmDshRecebimentos in 'Report\uFrmDshRecebimentos.pas' {FrmDshRecebimentos},
  uFrmRelMovimentacao in 'Report\uFrmRelMovimentacao.pas' {FrmRelMovimentacao},
  uFrmSegregadoBaixa in 'View\uFrmSegregadoBaixa.pas' {FrmSegregadoBaixa},
  uFrmSegregadoCausa in 'View\uFrmSegregadoCausa.pas' {FrmSegregadoCausa},
  SegregadoCausaCtrl in 'Controller\SegregadoCausaCtrl.pas',
  uFrmRelAuditoriaVolumes in 'Report\uFrmRelAuditoriaVolumes.pas' {FrmRelAuditoriaVolumes},
  uFrmRelAuditoriaCortes in 'Report\uFrmRelAuditoriaCortes.pas' {FrmRelAuditoriaCortes},
  Services.Perfil in 'src\Services\Services.Perfil.pas' {ServicePerfil: TDataModule},
  Views.Pequisa.Perfil in 'src\Views\Views.Pequisa.Perfil.pas' {FrmPesquisaPerfil},
  uFrmCadCategoria in 'View\uFrmCadCategoria.pas' {FrmCadCategoria},
  ProdutoLinhaCtrl in 'Controller\ProdutoLinhaCtrl.pas',
  ProdutoLinhaClass in 'Model\ProdutoLinhaClass.pas',
  uFrmProdutoLinha in 'View\uFrmProdutoLinha.pas' {FrmProdutoLinha},
  uFrmAutorizarOperacao in 'View\uFrmAutorizarOperacao.pas' {FrmAutorizarOperacao},
  uFrmDshVolumesEvolucao in 'Report\uFrmDshVolumesEvolucao.pas' {FrmDshVolumesEvolucao},
  Views.Pequisa.Unidades in 'src\Views\Views.Pequisa.Unidades.pas' {FrmPesquisaUnidades},
  Services.Unidades in 'src\Services\Services.Unidades.pas' {ServiceUnidades: TDataModule},
  Services.Caixas in 'src\Services\Services.Caixas.pas' {ServiceCaixas: TDataModule},
  uFrmMonitorLog in 'View\uFrmMonitorLog.pas' {FrmMonitorLog},
  MonitorLogCtrl in 'Controller\MonitorLogCtrl.pas',
  uFrmDshInventarios in 'Report\uFrmDshInventarios.pas' {FrmDshInventarios},
  uFrmRelListaInventario in 'Report\uFrmRelListaInventario.pas' {FrmRelListaInventario},
  uFrmAuditoriaAcompanhamentoCheckIn in 'Report\uFrmAuditoriaAcompanhamentoCheckIn.pas' {FrmAuditoriaAcompanhamentoCheckIn},
  uFrmRelControleArmazenagem in 'Report\uFrmRelControleArmazenagem.pas' {FrmRelControleArmazenagem},
  uFrmRelUsuarios in 'Report\uFrmRelUsuarios.pas' {FrmRelUsuarios},
  Views.Pequisa.Usuarios in 'src\Views\Views.Pequisa.Usuarios.pas' {FrmPesquisaUsuario},
  Services.Usuarios in 'src\Services\Services.Usuarios.pas' {ServiceUsuario: TDataModule},
  Services.Funcionalidades in 'src\Services\Services.Funcionalidades.pas' {ServiceFuncionalidade: TDataModule},
  Views.Pesquisa.Funcionalidades in 'src\Views\Views.Pesquisa.Funcionalidades.pas' {FrmPesquisaFuncionalidade};

{$R *.res}

Var HprevHist : HWND;
begin
  HprevHist := FindWindow(Nil, PChar('eXactWMS® - Rhemasys Soluções (63) 9 9240-6343'));
  if HprevHist = 0 then begin
     Application.Initialize;
     Application.MainFormOnTaskbar := True;
     Application.Title := 'eXactWMS® - Rhemasys Soluções (63) 9 9240-6343';
     Application.Name  := 'eXactWMS';
     Application.CreateForm(TDmeXactWMS, DmeXactWMS);
     Application.CreateForm(TFrmeXactWMS, FrmeXactWMS);
     Application.Run;
  end
  Else
     MessageDlg('eXactWMS® já está ativado. Não pode ter mais de uma instância ativa!',MtInformation,[MbOk],0);
end.
