program Server;
{$APPTYPE GUI}
uses
  Vcl.Forms,
  Web.WebReq,
  IdHTTPWebBrokerBridge,
  JOSE.Builder in '..\..\Lib\JWT\JOSE.Builder.pas',
  JOSE.Consumer in '..\..\Lib\JWT\JOSE.Consumer.pas',
  JOSE.Consumer.Validators in '..\..\Lib\JWT\JOSE.Consumer.Validators.pas',
  JOSE.Context in '..\..\Lib\JWT\JOSE.Context.pas',
  JOSE.Core.Base in '..\..\Lib\JWT\JOSE.Core.Base.pas',
  JOSE.Core.Builder in '..\..\Lib\JWT\JOSE.Core.Builder.pas',
  JOSE.Core.JWA.Compression in '..\..\Lib\JWT\JOSE.Core.JWA.Compression.pas',
  JOSE.Core.JWA.Encryption in '..\..\Lib\JWT\JOSE.Core.JWA.Encryption.pas',
  JOSE.Core.JWA.Factory in '..\..\Lib\JWT\JOSE.Core.JWA.Factory.pas',
  JOSE.Core.JWA in '..\..\Lib\JWT\JOSE.Core.JWA.pas',
  JOSE.Core.JWA.Signing in '..\..\Lib\JWT\JOSE.Core.JWA.Signing.pas',
  JOSE.Core.JWE in '..\..\Lib\JWT\JOSE.Core.JWE.pas',
  JOSE.Core.JWK in '..\..\Lib\JWT\JOSE.Core.JWK.pas',
  JOSE.Core.JWS in '..\..\Lib\JWT\JOSE.Core.JWS.pas',
  JOSE.Core.JWT in '..\..\Lib\JWT\JOSE.Core.JWT.pas',
  JOSE.Core.Parts in '..\..\Lib\JWT\JOSE.Core.Parts.pas',
  JOSE.Encoding.Base64 in '..\..\Lib\JWT\JOSE.Encoding.Base64.pas',
  JOSE.Hashing.HMAC in '..\..\Lib\JWT\JOSE.Hashing.HMAC.pas',
  JOSE.OpenSSL.Headers in '..\..\Lib\JWT\JOSE.OpenSSL.Headers.pas',
  JOSE.Signing.Base in '..\..\Lib\JWT\JOSE.Signing.Base.pas',
  JOSE.Signing.ECDSA in '..\..\Lib\JWT\JOSE.Signing.ECDSA.pas',
  JOSE.Signing.RSA in '..\..\Lib\JWT\JOSE.Signing.RSA.pas',
  JOSE.Types.Arrays in '..\..\Lib\JWT\JOSE.Types.Arrays.pas',
  JOSE.Types.Bytes in '..\..\Lib\JWT\JOSE.Types.Bytes.pas',
  JOSE.Types.JSON in '..\..\Lib\JWT\JOSE.Types.JSON.pas',
  JOSE.Types.Utils in '..\..\Lib\JWT\JOSE.Types.Utils.pas',
  FrmServer in 'FrmServer.pas' {Form1},
  Server.Server.Attributes in '..\..\lib\ConcordiaServer\Server.Server.Attributes.pas',
  Server.Server.Authentication in '..\..\lib\ConcordiaServer\Server.Server.Authentication.pas',
  Server.Server.Config in '..\..\lib\ConcordiaServer\Server.Server.Config.pas',
  Server.Server.Connection in '..\..\lib\ConcordiaServer\Server.Server.Connection.pas',
  Server.Server.DAO in '..\..\lib\ConcordiaServer\Server.Server.DAO.pas',
  Server.Server.Log in '..\..\lib\ConcordiaServer\Server.Server.Log.pas',
  Server.Server.Message in '..\..\lib\ConcordiaServer\Server.Server.Message.pas',
  Server.Server.MessageList in '..\..\lib\ConcordiaServer\Server.Server.MessageList.pas',
  Server.Server.ResourceBaseClass in '..\..\lib\ConcordiaServer\Server.Server.ResourceBaseClass.pas',
  Server.Server.ServerConsole in '..\..\lib\ConcordiaServer\Server.Server.ServerConsole.pas',
  Server.Server.Token in '..\..\lib\ConcordiaServer\Server.Server.Token.pas',
  Server.Server.WebModule in '..\..\lib\ConcordiaServer\Server.Server.WebModule.pas' {WebModuleApi: TWebModule},
  Server.Utils.Criptografia in '..\..\lib\Utils\Server.Utils.Criptografia.pas',
  Server.Server.Interfaces.Authentication in '..\..\lib\ConcordiaServer\Interfaces\Server.Server.Interfaces.Authentication.pas',
  Server.Server.Constants in '..\..\lib\ConcordiaServer\Server.Server.Constants.pas',
  Resources.Cargos in '..\..\resources\Resources.Cargos.pas',
  Resources.ColaboradorAfastamentoFerias in '..\..\resources\Resources.ColaboradorAfastamentoFerias.pas',
  Resources.ColaboradorBancoHoraExtras in '..\..\resources\Resources.ColaboradorBancoHoraExtras.pas',
  Resources.ColaboradorDemissao in '..\..\resources\Resources.ColaboradorDemissao.pas',
  Resources.Colaboradores in '..\..\resources\Resources.Colaboradores.pas',
  Resources.ColaboradorHorario in '..\..\resources\Resources.ColaboradorHorario.pas',
  Resources.ColaboradorLocaisTrabalho in '..\..\resources\Resources.ColaboradorLocaisTrabalho.pas',
  Resources.DepartamentoFluxoAprovacao in '..\..\resources\Resources.DepartamentoFluxoAprovacao.pas',
  Resources.Departamentos in '..\..\resources\Resources.Departamentos.pas',
  Resources.EmpresaPlanos in '..\..\resources\Resources.EmpresaPlanos.pas',
  Resources.Empresas in '..\..\resources\Resources.Empresas.pas',
  Resources.Feriados in '..\..\resources\Resources.Feriados.pas',
  Resources.Funcoes in '..\..\resources\Resources.Funcoes.pas',
  Resources.LocaisTrabalho in '..\..\resources\Resources.LocaisTrabalho.pas',
  Resources.MotivosDemissao in '..\..\resources\Resources.MotivosDemissao.pas',
  Resources.PerfilFuncoes in '..\..\resources\Resources.PerfilFuncoes.pas',
  Resources.Perfis in '..\..\resources\Resources.Perfis.pas',
  Resources.Planos in '..\..\resources\Resources.Planos.pas',
  Resources.RevendaPlanos in '..\..\resources\Resources.RevendaPlanos.pas',
  Resources.Revendas in '..\..\resources\Resources.Revendas.pas',
  Resources.SenhaReset in '..\..\resources\Resources.SenhaReset.pas',
  Resources.TiposOcorrencias in '..\..\resources\Resources.TiposOcorrencias.pas',
  Resources.TiposSolicitacoes in '..\..\resources\Resources.TiposSolicitacoes.pas',
  Resources.Usuarios in '..\..\resources\Resources.Usuarios.pas',
  Server.Server.Records in '..\..\lib\ConcordiaServer\Server.Server.Records.pas',
  Server.Server.MapperTable in '..\..\lib\ConcordiaServer\MapperTable\Server.Server.MapperTable.pas',
  Server.Server.Mapper in '..\..\lib\ConcordiaServer\MapperTable\Server.Server.Mapper.pas',
  Swager.Json.Body in '..\..\lib\Swager\Swager.Json.Body.pas',
  Swager.Json.Definitions in '..\..\lib\Swager\Swager.Json.Definitions.pas',
  Swager.Json.DTO in '..\..\lib\Swager\Swager.Json.DTO.pas',
  Swager.Json.Paths in '..\..\lib\Swager\Swager.Json.Paths.pas',
  Swager.ResourceBaseClass in '..\..\lib\Swager\Swager.ResourceBaseClass.pas',
  Server.Server.Swagger in '..\..\lib\ConcordiaServer\Server.Server.Swagger.pas',
  Server.Server.AngularModel in '..\..\lib\ConcordiaServer\Server.Server.AngularModel.pas',
  Server.Utils.Strings in '..\..\lib\ConcordiaServer\Server.Utils.Strings.pas',
  Resources.Authorization in '..\..\resources\Resources.Authorization.pas',
  Resources.SendEmail in '..\..\resources\Resources.SendEmail.pas',
  Server.Utils.SendMail2 in '..\..\lib\Utils\Server.Utils.SendMail2.pas',
  asn1util in '..\..\lib\SynapseMail\asn1util.pas',
  blcksock in '..\..\lib\SynapseMail\blcksock.pas',
  clamsend in '..\..\lib\SynapseMail\clamsend.pas',
  dnssend in '..\..\lib\SynapseMail\dnssend.pas',
  ftpsend in '..\..\lib\SynapseMail\ftpsend.pas',
  ftptsend in '..\..\lib\SynapseMail\ftptsend.pas',
  httpsend in '..\..\lib\SynapseMail\httpsend.pas',
  imapsend in '..\..\lib\SynapseMail\imapsend.pas',
  ldapsend in '..\..\lib\SynapseMail\ldapsend.pas',
  mimeinln in '..\..\lib\SynapseMail\mimeinln.pas',
  mimemess in '..\..\lib\SynapseMail\mimemess.pas',
  mimepart in '..\..\lib\SynapseMail\mimepart.pas',
  nntpsend in '..\..\lib\SynapseMail\nntpsend.pas',
  pingsend in '..\..\lib\SynapseMail\pingsend.pas',
  pop3send in '..\..\lib\SynapseMail\pop3send.pas',
  slogsend in '..\..\lib\SynapseMail\slogsend.pas',
  smtpsend in '..\..\lib\SynapseMail\smtpsend.pas',
  snmpsend in '..\..\lib\SynapseMail\snmpsend.pas',
  sntpsend in '..\..\lib\SynapseMail\sntpsend.pas',
  ssl_openssl in '..\..\lib\SynapseMail\ssl_openssl.pas',
  ssl_openssl_lib in '..\..\lib\SynapseMail\ssl_openssl_lib.pas',
  ssl_openssl11_lib in '..\..\lib\SynapseMail\ssl_openssl11_lib.pas',
  synachar in '..\..\lib\SynapseMail\synachar.pas',
  synacode in '..\..\lib\SynapseMail\synacode.pas',
  synacrypt in '..\..\lib\SynapseMail\synacrypt.pas',
  synadbg in '..\..\lib\SynapseMail\synadbg.pas',
  synafpc in '..\..\lib\SynapseMail\synafpc.pas',
  synaicnv in '..\..\lib\SynapseMail\synaicnv.pas',
  synaip in '..\..\lib\SynapseMail\synaip.pas',
  synamisc in '..\..\lib\SynapseMail\synamisc.pas',
  synaser in '..\..\lib\SynapseMail\synaser.pas',
  synautil in '..\..\lib\SynapseMail\synautil.pas',
  synsock in '..\..\lib\SynapseMail\synsock.pas',
  tlntsend in '..\..\lib\SynapseMail\tlntsend.pas',
  WkMail in '..\..\lib\Utils\WkMail.pas',
  Utils.Helpers in '..\..\lib\Utils\Utils.Helpers.pas',
  Resources.RegistroPonto in '..\..\resources\Resources.RegistroPonto.pas',
  Resources.RegistroPontoFoto in '..\..\resources\Resources.RegistroPontoFoto.pas',
  Resources.ApuracaoPonto in '..\..\resources\Resources.ApuracaoPonto.pas',
  Utils.JsonSearchToWhere in '..\..\lib\Utils\Utils.JsonSearchToWhere.pas',
  Resources.UsuarioCamadas in '..\..\resources\Resources.UsuarioCamadas.pas',
  Resources.Solicitacoes in '..\..\resources\Resources.Solicitacoes.pas',
  Resources.SolicitacoesAprovacao in '..\..\resources\Resources.SolicitacoesAprovacao.pas',
  Resources.ApuracaoPontoOcorrencias in '..\..\resources\Resources.ApuracaoPontoOcorrencias.pas',
  Server.Utils.SectionVariables in '..\..\lib\Utils\Server.Utils.SectionVariables.pas',
  Resources.UsuarioSenha in '..\..\resources\Resources.UsuarioSenha.pas',
  Repository.AlterarSenha in '..\..\Repository\Repository.AlterarSenha.pas',
  Server.Server.Interfaces.AlterarSenha in '..\..\lib\ConcordiaServer\Interfaces\Server.Server.Interfaces.AlterarSenha.pas';

{$R *.res}
begin
  if WebRequestHandler <> nil then
    WebRequestHandler.WebModuleClass := WebModuleClass;
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
