program UpdateServer;

{$APPTYPE CONSOLE}


uses
  Server.ServerConsole in '..\..\lib\Server\Server.ServerConsole.pas',
  System.SysUtils,
  System.Classes,
  System.Types,
  IPPeerServer,
  IPPeerAPI,
  IdHTTPWebBrokerBridge,
  Web.WebReq,
  Web.WebBroker,
  Datasnap.DSSession,
  JOSE.Builder in '..\..\Lib\JWT\JOSE.Builder.pas',
  JOSE.Consumer in '..\..\Lib\JWT\JOSE.Consumer.pas',
  JOSE.Consumer.Validators in '..\..\Lib\JWT\JOSE.Consumer.Validators.pas',
  JOSE.Context in '..\..\Lib\JWT\JOSE.Context.pas',
  JOSE.Core.Base in '..\..\Lib\JWT\JOSE.Core.Base.pas',
  JOSE.Core.Builder in '..\..\Lib\JWT\JOSE.Core.Builder.pas',
  JOSE.Core.JWA.Compression in '..\..\Lib\JWT\JOSE.Core.JWA.Compression.pas',
  JOSE.Core.JWA.Encryption in '..\..\Lib\JWT\JOSE.Core.JWA.Encryption.pas',
  JOSE.Core.JWA.Factory in '..\..\Lib\JWT\JOSE.Core.JWA.Factory.pas',
  JOSE.Core.JWA in '..\..\Lib\JWT\JOSE.Core.JWA.pas',
  JOSE.Core.JWA.Signing in '..\..\Lib\JWT\JOSE.Core.JWA.Signing.pas',
  JOSE.Core.JWE in '..\..\Lib\JWT\JOSE.Core.JWE.pas',
  JOSE.Core.JWK in '..\..\Lib\JWT\JOSE.Core.JWK.pas',
  JOSE.Core.JWS in '..\..\Lib\JWT\JOSE.Core.JWS.pas',
  JOSE.Core.JWT in '..\..\Lib\JWT\JOSE.Core.JWT.pas',
  JOSE.Core.Parts in '..\..\Lib\JWT\JOSE.Core.Parts.pas',
  JOSE.Encoding.Base64 in '..\..\Lib\JWT\JOSE.Encoding.Base64.pas',
  JOSE.Hashing.HMAC in '..\..\Lib\JWT\JOSE.Hashing.HMAC.pas',
  JOSE.OpenSSL.Headers in '..\..\Lib\JWT\JOSE.OpenSSL.Headers.pas',
  JOSE.Signing.Base in '..\..\Lib\JWT\JOSE.Signing.Base.pas',
  JOSE.Signing.ECDSA in '..\..\Lib\JWT\JOSE.Signing.ECDSA.pas',
  JOSE.Signing.RSA in '..\..\Lib\JWT\JOSE.Signing.RSA.pas',
  JOSE.Types.Arrays in '..\..\Lib\JWT\JOSE.Types.Arrays.pas',
  JOSE.Types.Bytes in '..\..\Lib\JWT\JOSE.Types.Bytes.pas',
  JOSE.Types.JSON in '..\..\Lib\JWT\JOSE.Types.JSON.pas',
  JOSE.Types.Utils in '..\..\Lib\JWT\JOSE.Types.Utils.pas',
  Server.Attributes in '..\..\lib\Server\Server.Attributes.pas',
  Server.Authentication in '..\..\lib\Server\Server.Authentication.pas',
  Server.Config in '..\..\lib\Server\Server.Config.pas',
  Server.Connection in '..\..\lib\Server\Server.Connection.pas',
  Server.DAO in '..\..\lib\Server\Server.DAO.pas',
  Server.Log in '..\..\lib\Server\Server.Log.pas',
  Server.Message in '..\..\lib\Server\Server.Message.pas',
  Server.MessageList in '..\..\lib\Server\Server.MessageList.pas',
  Server.ResourceBaseClass in '..\..\lib\Server\Server.ResourceBaseClass.pas',
  Server.Token in '..\..\lib\Server\Server.Token.pas',
  Server.WebModule in '..\..\lib\Server\Server.WebModule.pas' {WebModuleApi: TWebModule},
  Server.Utils.Criptografia in '..\..\lib\Utils\Server.Utils.Criptografia.pas',
  Server.Constants in '..\..\lib\Server\Server.Constants.pas',
  Server.Records in '..\..\lib\Server\Server.Records.pas',
  Swager.Json.DTO in '..\..\lib\Swager\Swager.Json.DTO.pas',
  Swager.Json.Body in '..\..\lib\Swager\Swager.Json.Body.pas',
  asn1util in '..\..\lib\SynapseMail\asn1util.pas',
  blcksock in '..\..\lib\SynapseMail\blcksock.pas',
  clamsend in '..\..\lib\SynapseMail\clamsend.pas',
  dnssend in '..\..\lib\SynapseMail\dnssend.pas',
  ftpsend in '..\..\lib\SynapseMail\ftpsend.pas',
  ftptsend in '..\..\lib\SynapseMail\ftptsend.pas',
  httpsend in '..\..\lib\SynapseMail\httpsend.pas',
  imapsend in '..\..\lib\SynapseMail\imapsend.pas',
  ldapsend in '..\..\lib\SynapseMail\ldapsend.pas',
  mimeinln in '..\..\lib\SynapseMail\mimeinln.pas',
  mimemess in '..\..\lib\SynapseMail\mimemess.pas',
  mimepart in '..\..\lib\SynapseMail\mimepart.pas',
  nntpsend in '..\..\lib\SynapseMail\nntpsend.pas',
  pingsend in '..\..\lib\SynapseMail\pingsend.pas',
  pop3send in '..\..\lib\SynapseMail\pop3send.pas',
  slogsend in '..\..\lib\SynapseMail\slogsend.pas',
  smtpsend in '..\..\lib\SynapseMail\smtpsend.pas',
  snmpsend in '..\..\lib\SynapseMail\snmpsend.pas',
  sntpsend in '..\..\lib\SynapseMail\sntpsend.pas',
  ssl_openssl in '..\..\lib\SynapseMail\ssl_openssl.pas',
  ssl_openssl_lib in '..\..\lib\SynapseMail\ssl_openssl_lib.pas',
  ssl_openssl11_lib in '..\..\lib\SynapseMail\ssl_openssl11_lib.pas',
  synachar in '..\..\lib\SynapseMail\synachar.pas',
  synacode in '..\..\lib\SynapseMail\synacode.pas',
  synacrypt in '..\..\lib\SynapseMail\synacrypt.pas',
  synadbg in '..\..\lib\SynapseMail\synadbg.pas',
  synafpc in '..\..\lib\SynapseMail\synafpc.pas',
  synaicnv in '..\..\lib\SynapseMail\synaicnv.pas',
  synaip in '..\..\lib\SynapseMail\synaip.pas',
  synamisc in '..\..\lib\SynapseMail\synamisc.pas',
  synaser in '..\..\lib\SynapseMail\synaser.pas',
  synautil in '..\..\lib\SynapseMail\synautil.pas',
  synsock in '..\..\lib\SynapseMail\synsock.pas',
  tlntsend in '..\..\lib\SynapseMail\tlntsend.pas',
  Server.Util in '..\..\lib\Utils\Server.Util.pas',
  Server.Interfaces.SendEMail in '..\..\lib\Server\Interfaces\Server.Interfaces.SendEMail.pas',
  Server.Swagger in '..\..\lib\Server\Server.Swagger.pas',
  Server.Utils.SectionVariables in '..\..\lib\Utils\Server.Utils.SectionVariables.pas',
  Server.Utils.JsonSearchToWhere in '..\..\lib\Utils\Server.Utils.JsonSearchToWhere.pas',
  Server.AngularModel in '..\..\lib\Server\Server.AngularModel.pas',
  Server.Utils.Strings in '..\..\lib\Utils\Server.Utils.Strings.pas',
  Swager.Json.Paths in '..\..\lib\Swager\Swager.Json.Paths.pas',
  ServerMail in '..\..\lib\Utils\ServerMail.pas',
  Repository.SendEMail in '..\..\Repository\Repository.SendEMail.pas',
  Server.Utils.SendMail2 in '..\..\lib\Utils\Server.Utils.SendMail2.pas',
  Resources.Cargas in '..\..\resources\Resources.Cargas.pas',
  Resources.Categorias in '..\..\resources\Resources.Categorias.pas',
  Resources.Configuracao in '..\..\resources\Resources.Configuracao.pas',
  Resources.Estoque in '..\..\resources\Resources.Estoque.pas',
  Resources.Kardex in '..\..\resources\Resources.Kardex.pas',
  Resources.Pedido in '..\..\resources\Resources.Pedido.pas',
  Resources.Pessoa in '..\..\resources\Resources.Pessoa.pas',
  Resources.Produto in '..\..\resources\Resources.Produto.pas',
  Resources.Rotas in '..\..\resources\Resources.Rotas.pas',
  Resources.Usuarios in '..\..\resources\Resources.Usuarios.pas',
  Resources.Configupdate in '..\..\resources\Resources.Configupdate.pas',
  Repository.GetVersion in '..\..\Repository\Repository.GetVersion.pas',
  Repository.UploadApk in '..\..\Repository\Repository.UploadApk.pas',
  Repository.Authorization in '..\..\Repository\Repository.Authorization.pas',
  Server.Interfaces.Authentication in '..\..\lib\Server\Interfaces\Server.Interfaces.Authentication.pas';

begin
  try
    if WebRequestHandler <> nil then
      WebRequestHandler.WebModuleClass := WebModuleClass;
    Writeln(cLogoAscArt);
    Writeln('Iniciando na porta 8081');
    StartClassGroup(TComponent);
    ActivateClassGroup(TComponent);
    globalServer.RunServer(8081);

  except
    on e: exception do
      Writeln(e.ClassName, ': ', e.Message);
  end;

end.
